### ISSUE TITLE
[Feat] 채팅 - Front

### ISSUE THREAD

**Issue by ohjooyeong** [kimth007kim/crewcrew#7]
## Describe 
채팅 기능의 프론트 영역을 구현합니다. 기획/디자인 및 백엔드와 소통 후 자세하게 구현하도록 하겠습니다.

## To-do
- [x] 채팅 리스트 페이지 디자인
  - [x] 웹
  - [x] 모바일
- [x] 채팅 리스트 체크 기능
- [x] 채팅 리스트 삭제 기능
- [x] 채팅 상세 페이지 디자인
  - [x] 웹
  - [x] 모바일
- [x] 채팅 검색 기능 
- [x] 웹소켓 연결
- [x] 채팅 기능
  - [x] 보내기
  - [x] 받기
  - [x] 줄바꿈 처리
- [x] 채팅 박스 섹션 만들어서 날짜별로 만들기
- [x] 스크롤 상세 기능
  - [x] 첫 렌더링 시 스크롤 맨아래
  - [x] 내가 채팅 보낼 때 스크롤 맨 아래
  - [x] 남이 채팅 보낼 때 일정스크롤 영역 벗어나면 스크롤 안되게 하기
- [x] 리버스 인피니트 스크롤링 - 프론트
- [x] 채팅방 데이터 연결
  - [x] 채팅 리스트
  - [x] 채팅 디테일

## ETC
API가 아직 구현 안됐으면 정크 값으로 넣기

**Comment by ohjooyeong** [comment]
## 고민 많이 한 것들

### 채팅 박스 섹션 만들어서 날짜별로 만들기 고민

1: 따로 utils함수로 만들어서 chatList의 전체값을 받아서 각 메시지의 date값을 바탕으로 키값을 만들고, 거기에 chat data들을 배열 형태로 넣어줌

```javascript
import dayjs from 'dayjs';

export default function makeSection(chatList) {
  const sections = {};
  chatList.forEach((chat) => {
    const monthDate = dayjs(chat.date).format('YYYY-MM-DD');
    if (Array.isArray(sections[monthDate])) {
      sections[monthDate].push(chat);
    } else {
      sections[monthDate] = [chat];
    }
  });
  return sections;
}
```

2: 각 값을 컴포넌트에서 객체 key값으로 돌려서 렌더링함.

```javascript
{Object.entries(chatSections).map(([date, chats]) => {
  return (
    <ChatDtWrapper key={date}>
      <DtDate>{dayjs(date).format('MM.DD')}</DtDate>
      {chats.map((chat) => (
        <ChatCard key={chat.messageId} data={chat}></ChatCard>
      ))}
    </ChatDtWrapper>
  );
})}
```

### 리버스 인피니트 스크롤링에 대해 고민
1: useState를 사용할까, swr을 사용할까 -> useSWRInfinite라는 메서드가 있어서 사용하기로함.
2: useSWRInfinite는 setSize를 프론트에서 사용해서 index를 갱신하고, 전에 값에다 계속 쌓는 방식이라 확실히 좋은듯함
3: data값이 기존 과는 다르게 배열로 준다는 것을 알았음. 기존 로직을 변경해서 구현해줘야 할 듯함.
```javascript
 const chatSections = makeSection(chatData && chatData.data ? [...chatData.data].reverse() : []);

=====>
// map으로 배열을 arrayData라는 값에 갱신해서 chatSections
  let chatSections = [];

  if (chatData) {
    const arrayData = chatData.map((data) => {
      return data.data;
    });
    chatSections = makeSection(arrayData ? arrayData.flat().reverse() : []);
  }
```

4: react-custom-scrollbars 라이브러리를 사용하기 때문에 좀 더 편했음 - 전에 스크롤 값을 기억하는 values값을 바탕으로 현재 스크롤 값에서 빼주면 되는 형태
```
const onScroll = useCallback((values) => {
  if (values.scrollTop === 0) {
    setSize((prevSize) => prevSize + 1).then(() => {
      // 스크롤 위치 유지
      const current = scrollRef?.current;
      current?.scrollTop(current?.getScrollHeight() - values.scrollHeight);
    });
  }
}, []);
```
5: 로직과는 다르게 인피니트 스크롤할 때마다 최하단으로 가는 버그가 있었는데 다른 로직과 충돌해서 그런거 였음. 예외처리하니까 정상 작동함.
